[package]
name = "nhop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nhop-ipc.workspace = true

arc-swap.workspace = true
argh.workspace = true
fs2.workspace = true
humantime.workspace = true
ipnet.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
socket2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-socks.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
